// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PoleClient is the client API for Pole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoleClient interface {
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
}

type poleClient struct {
	cc grpc.ClientConnInterface
}

func NewPoleClient(cc grpc.ClientConnInterface) PoleClient {
	return &poleClient{cc}
}

func (c *poleClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, "/Pole/Exec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoleServer is the server API for Pole service.
// All implementations must embed UnimplementedPoleServer
// for forward compatibility
type PoleServer interface {
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	mustEmbedUnimplementedPoleServer()
}

// UnimplementedPoleServer must be embedded to have forward compatible implementations.
type UnimplementedPoleServer struct {
}

func (UnimplementedPoleServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedPoleServer) mustEmbedUnimplementedPoleServer() {}

// UnsafePoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoleServer will
// result in compilation errors.
type UnsafePoleServer interface {
	mustEmbedUnimplementedPoleServer()
}

func RegisterPoleServer(s grpc.ServiceRegistrar, srv PoleServer) {
	s.RegisterService(&Pole_ServiceDesc, srv)
}

func _Pole_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoleServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pole/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoleServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pole_ServiceDesc is the grpc.ServiceDesc for Pole service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pole_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Pole",
	HandlerType: (*PoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _Pole_Exec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pb/pole.proto",
}
